-- ProgramFit assessment answer storage
-- Run this in Supabase SQL Editor.
-- The app currently identifies accounts by user_acc.username.

alter table if exists public.user_acc
  add column if not exists has_answered boolean not null default false;

create table if not exists public.assessment_attempts (
  id bigint generated by default as identity primary key,
  username text not null,
  status text not null default 'completed'
    check (status in ('in_progress', 'completed', 'abandoned')),
  phase1_answers jsonb not null default '[]'::jsonb,
  phase2_answers jsonb not null default '[]'::jsonb,
  confirmation_score integer not null default 0
    check (confirmation_score >= 0),
  top_department_code text,
  result_snapshot jsonb,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.assessment_answers (
  id bigint generated by default as identity primary key,
  attempt_id bigint not null references public.assessment_attempts(id) on delete cascade,
  username text not null,
  phase text not null check (phase in ('phase1', 'phase2', 'confirmation')),
  question_number integer not null check (question_number > 0),
  selected_option_index integer not null check (selected_option_index >= 0),
  selected_option_code text,
  selected_option_text text,
  created_at timestamptz not null default now(),
  unique (attempt_id, phase, question_number)
);

create index if not exists assessment_attempts_username_idx
  on public.assessment_attempts (username, created_at desc);

create index if not exists assessment_answers_username_idx
  on public.assessment_answers (username, created_at desc);

create index if not exists assessment_answers_attempt_idx
  on public.assessment_answers (attempt_id);

create or replace function public.mark_user_assessment_answered()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.status = 'completed' then
    update public.user_acc
    set has_answered = true
    where username = new.username;
  end if;
  return new;
end;
$$;

drop trigger if exists assessment_attempt_completed on public.assessment_attempts;
create trigger assessment_attempt_completed
after insert or update of status on public.assessment_attempts
for each row execute function public.mark_user_assessment_answered();

-- Helpful RPC for saving one completed assessment atomically.
create or replace function public.save_assessment_attempt(
  p_username text,
  p_phase1_answers jsonb,
  p_phase2_answers jsonb default '[]'::jsonb,
  p_confirmation_score integer default 0,
  p_top_department_code text default null,
  p_result_snapshot jsonb default null,
  p_answers jsonb default '[]'::jsonb
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_attempt_id bigint;
  v_answer jsonb;
begin
  if nullif(trim(p_username), '') is null then
    raise exception 'username is required';
  end if;

  if not exists (
    select 1 from public.user_acc where username = trim(p_username)
  ) then
    raise exception 'account not found';
  end if;

  insert into public.assessment_attempts (
    username,
    status,
    phase1_answers,
    phase2_answers,
    confirmation_score,
    top_department_code,
    result_snapshot,
    completed_at
  ) values (
    trim(p_username),
    'completed',
    coalesce(p_phase1_answers, '[]'::jsonb),
    coalesce(p_phase2_answers, '[]'::jsonb),
    greatest(coalesce(p_confirmation_score, 0), 0),
    p_top_department_code,
    p_result_snapshot,
    now()
  ) returning id into v_attempt_id;

  for v_answer in select value from jsonb_array_elements(coalesce(p_answers, '[]'::jsonb))
  loop
    insert into public.assessment_answers (
      attempt_id,
      username,
      phase,
      question_number,
      selected_option_index,
      selected_option_code,
      selected_option_text
    ) values (
      v_attempt_id,
      trim(p_username),
      v_answer->>'phase',
      (v_answer->>'question_number')::integer,
      (v_answer->>'selected_option_index')::integer,
      v_answer->>'selected_option_code',
      v_answer->>'selected_option_text'
    );
  end loop;

  return v_attempt_id;
end;
$$;

-- Do not grant this to anon/authenticated: custom username/password auth cannot
-- prove that the caller owns p_username. Call this function from a trusted
-- server or Edge Function using the service_role key.
revoke all on function public.save_assessment_attempt(text, jsonb, jsonb, integer, text, jsonb, jsonb)
from public, anon, authenticated;
grant execute on function public.save_assessment_attempt(text, jsonb, jsonb, integer, text, jsonb, jsonb)
to service_role;

-- Because this project uses custom username/password authentication rather than
-- Supabase Auth, database RLS cannot securely identify the current user.
-- Keep these tables disabled for direct client table access and write through
-- the RPC above, or move account authentication to Supabase Auth first.
alter table public.assessment_attempts enable row level security;
alter table public.assessment_answers enable row level security;

-- Do not add a broad public SELECT/INSERT policy here. A custom-auth Flutter
-- client must not be trusted to submit another username directly.
-- Recommended production setup: call this RPC from a trusted Edge Function,
-- or migrate user_acc accounts to Supabase Auth and add auth.uid()-based policies.
